# Generated by Django 4.1.7 on 2023-02-19 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
        ('comentarios', '__first__'),
        ('avaliacoes', '__first__'),
        ('atracoes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontoTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('atracoes', models.ManyToManyField(to='atracoes.atracao')),
                ('avaliacoes', models.ManyToManyField(to='avaliacoes.avaliacao')),
                ('comentarios', models.ManyToManyField(to='comentarios.comentario')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enderecos.endereco')),
            ],
        ),
    ]
