# Generated by Django 4.1.7 on 2023-02-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='user',
            new_name='usuario',
        ),
    ]
